### ISSUE TITLE
Feature request: Art and color scheme

### ISSUE THREAD

**Issue by guefra** [MeiNic/MenschAergereDichNicht#57]
Currently, there is this default looking grey background and some boring looking colors as players. There aren't any sprites for the players, a dice or a logo for the game either. I request to draw 

- [x] Player sprites (for the game)
- [x] Logo (for the GitHub page or other)
- [x] Icon (for the window or taskbar)
- [x] Dice (to replace the "roll the dice" button)
- [x] Fields (for the players to move on)
- [x] Board (for the fields and the player to be on)

as well as choose the right colors for the application (I will use the ones from the [Catppuccin color pallet](https://github.com/catppuccin/palette)) and other art which you may want me to make.

**Comment by MeiNic** [comment]
Hello @guefra,
thanks for the offer to paint graphics for the game and the complete project. When implementing various things, I currently do not know how to implement them. But the "problem" should be solvable quite quickly.

Some helpful information for the graphics:
- The JFrame of the `gameBoardGui` has the size of width: `1400` pixel, height: `940` pixel (you could change this if you want
- The coordinates of all the circles could be found in the class `gameBoardGui.java` in the arrays set globally in the top of the class (These coordinates could also be changed; we only should know the new values for the user clicks)

Feel free to take your time with the creation of the graphics. If there are any problems coming up during the process, feel free to contact us.

**Comment by guefra** [comment]
Thank you @MeiNic!

I already drew the art, now I think I'll first make an example of the board with all components and second try to implement it into the game.

**Comment by guefra** [comment]
If it's possible, I would suggest to use the font [JetBrains Mono](https://www.jetbrains.com/de-de/lp/mono/), which fits the style of the game art very well. By the way, the finished art you can see here: https://github.com/guefra/MenschAergereDichNicht/tree/artwork/artwork. 

If there is something, you would change or some art you may will need extra (like buttons or other), please let me know.

**Comment by MeiNic** [comment]
> If it's possible, I would suggest to use the font [JetBrains Mono](https://www.jetbrains.com/de-de/lp/mono/), which fits the style of the game art very well.

This font looks nice, I didn't know it till your suggestion. I'm going to implement it within this week for all texts.
> By the way, the finished art you can see here: https://github.com/guefra/MenschAergereDichNicht/tree/artwork/artwork.

The finished art looks amazing, no comparison to the "old" java graphics. I think there are no more changes needed now.
> If there is something, you would change or some art you may will need extra (like buttons or other), please let me know.

I just had the idea, to bring this layout to the hole UI. I think we just need the background for the other JFrames and the buttons could be replaced with the artwork. To replace the elements, the user inserts a number, checks a checkbox or inserts a String is not really possible. 
Therefore, we just need some buttons with the text:
- "start game" (in `Landingpage.java`)
- "next Player" (in `GameBoardGui.java`)
- "done" (in `Rules.java`)

If you need some help with the impementation, just ask. If there are bigger problems with the impementation I could do it either.

**Comment by guefra** [comment]
Hi,

thank you for your reply. @guemax just said, that before implemnting the graphics in the code, the backend has to be changend (I think he'll do this, because I'm not very into Java), so the code doesn't have to be changed every time, when the sprites are. So I just do some more art, while he changes the backend

**Comment by MeiNic** [comment]
Hi,
thanks for your reply. I actually have no idea, what has to be changes in the `backEnd`-class. 
@guemax you said, that changes in the `backEnd.java` file are needed. Are these changes espicially for the grafic implemtation, or not. My idea was ist to simply replace all the old GUI-Elements with the new ones.

**Comment by guemax** [comment]
My goal on [guemax:refactor-gui-backend-interaction](https://github.com/guemax/MenschAergereDichNicht/tree/refactor-gui-backend-interaction) is to make `BackEnd` completely unaware of `GameBoardGui`. Currently these two classes are heavily interwoven, which results in having to often make changes to both, even though you just wanted to alter some graphics, as (partially) seen in #54.

This way, @guefra can (relatively) easily change the look of the UI, without having to work in BackEnd.java as well. Because I will continue refactoring this file in the next few days even more, we won't thwart each other during the process.

**Comment by MeiNic** [comment]
Sounds good,
I just had a shortlook to the changes in your branch. I would recomend to change html to hex. (I know that in html hex color codes are used, but with the change you can easily prevent any possible confusion).

**Comment by MeiNic** [comment]
@guefra thanks for the PR with the image files
I have one questions:  I don't get the difference between the files called `field-xxx-inner.jpg` and the file called `field-xxx.jpg`

Thanks in advance 
MeiNic

**Comment by MeiNic** [comment]
@guefra I started with the implementation of your graphic elements. I’m about to finish the landingpage. I just discovered that for the `start game`-button it would be nice if it turns red or green depending on a state. These two buttons should have the name `button-hovered-green` and `button-hovered-red`.
Many thanks in advance
MeiNic

PS: You can see my progress in the branch [newUI](https://github.com/MeiNic/MenschAergereDichNicht/tree/newUI) in this repositorie

**Comment by guefra** [comment]
Hi @Meinic ,

thank you very much for implementing my artwork into the game because I can't code in Java. As you may have noticed, I just pushed a new commit on my fork on the branch artwork. I wish you fun with your further coding!

**Comment by MeiNic** [comment]
All grapics parts of the game got the new design (see #84 and #87). Later the icon could be used.
